version: '3'

env:
  DIST: '{{.DIST | default "dev"}}'
  FUNCTION_CODE_PATH: '{{.TASKFILE_DIR}}/function-app/code'
  FUNCTION_ZIP_DIR: '{{.TASKFILE_DIR}}/.tf-function-app'

tasks:
  get_function_app_hash:
    cmds:
      - ./zip_function_app_creation/get_function_app_hash.sh {{OS}} ${FUNCTION_CODE_PATH}
    silent: true
  
  create_function_app_zip:
    cmds:
      - ./zip_function_app_creation/create_function_app_zip.sh {{OS}} ${FUNCTION_CODE_PATH} ${FUNCTION_ZIP_DIR}
    desc: Generate function app zip

  upload_to_storage_accounts:
    env:
      RESOURCE_GROUP: weka-tf-functions
      REGIONS_FILE_DIR: '{{.TASKFILE_DIR}}/supported_regions' # File containing list of supported Azure regions
    deps: [create_function_app_zip]
    cmds:
      - ./zip_function_app_creation/upload_to_storage_accounts.sh ${REGIONS_FILE_DIR} ${DIST} {{OS}} ${FUNCTION_CODE_PATH} ${FUNCTION_ZIP_DIR} ${RESOURCE_GROUP}
    desc: Upload zip to multiple Azure Storage accounts

  write_function_hash_to_variables:
    cmds:
      - ./zip_function_app_creation/write_function_hash_to_variables.sh {{OS}} ${FUNCTION_CODE_PATH}

  create_and_upload_zip:
    preconditions:
      - sh: "[ $DIST == 'dev' ] || [ $DIST == 'release' ]"
        msg: "Valid value for DIST is one of the following: dev, release."
    deps: [upload_to_storage_accounts, write_function_hash_to_variables]
    cmds:
      - echo "Ran distribution for $DIST"
    desc: Generate function app zip and upload to Azure Storage accounts
