version: '3'

env:
  DIST: '{{.DIST | default "dev"}}'
  FUNCTION_CODE_PATH: '{{.TASKFILE_DIR}}/app/code'
  FUNCTION_BIN_DIR: '{{.TASKFILE_DIR}}/.tf-binaries'

tasks:
  get_code_hash:
    cmds:
      - ./binary_app_creation/get_code_hash.sh {{OS}} ${FUNCTION_CODE_PATH}
    silent: true
  
  create_binary:
    cmds:
      - ./binary_app_creation/create_binary.sh {{OS}} ${FUNCTION_CODE_PATH} ${FUNCTION_BIN_DIR}
    desc: Generate function app bin

  upload_to_storage_accounts:
    env:
      RESOURCE_GROUP: weka-tf-functions
      REGIONS_FILE_DIR: '{{.TASKFILE_DIR}}/supported_regions' # File containing list of supported Azure regions
    deps: [create_binary]
    cmds:
      - ./binary_app_creation/upload_to_storage_accounts.sh ${REGIONS_FILE_DIR} ${DIST} {{OS}} ${FUNCTION_CODE_PATH} ${FUNCTION_BIN_DIR} ${RESOURCE_GROUP}
    desc: Upload bin to multiple Azure Storage accounts

  write_code_hash_to_variables:
    cmds:
      - ./binary_app_creation/write_code_hash_to_variables.sh {{OS}} ${FUNCTION_CODE_PATH}

  create_and_upload_bin:
    preconditions:
      - sh: "[ $DIST == 'dev' ] || [ $DIST == 'release' ]"
        msg: "Valid value for DIST is one of the following: dev, release."
    deps: [upload_to_storage_accounts, write_code_hash_to_variables]
    cmds:
      - echo "Ran distribution for $DIST"
    desc: Generate function app bin and upload to Azure Storage accounts
