version: '3'

env:
  FUNCTION_CODE_PATH: '{{.TASKFILE_DIR}}/function-app/code'
  FUNCTION_BINS_DIR: '{{.TASKFILE_DIR}}/.tf-function-app'
  AZ_RESOURCE_GROUP: '{{.AZ_RESOURCE_GROUP | default "assaf"}}'
  AZ_STORAGE_ACCOUNT: '{{.AZ_STORAGE_ACCOUNT | default "wekamanagement"}}'
  AZ_CONTAINER_NAME: '{{.AZ_CONTAINER_NAME | default "binaries"}}'

tasks:
  get_function_app_hash:
    cmds:
      - ./zip_function_app_creation/get_function_app_hash.sh {{OS}} ${FUNCTION_CODE_PATH}
    silent: true
  
  create_function_binarie:
    cmds:
      - ./zip_function_app_creation/create_function_binarie.sh {{OS}} ${FUNCTION_CODE_PATH} ${FUNCTION_BINS_DIR}
    desc: Generate function app binarie

  upload_to_storage_account:
    env:
      REGIONS_FILE_DIR: '{{.TASKFILE_DIR}}/supported_regions' # File containing list of supported Azure regions
    deps: [create_function_binarie]
    cmds:
      - ./zip_function_app_creation/upload_to_single_sa.sh {{OS}} ${FUNCTION_CODE_PATH} ${FUNCTION_BINS_DIR} ${AZ_RESOURCE_GROUP} ${AZ_STORAGE_ACCOUNT} ${AZ_CONTAINER_NAME}
    desc: Upload bin to multiple Azure Storage accounts

  write_function_hash_to_variables:
    cmds:
      - ./zip_function_app_creation/write_function_hash_to_variables.sh {{OS}} ${FUNCTION_CODE_PATH}

  create_and_upload_bin:
    deps: [upload_to_storage_account, write_function_hash_to_variables]
    cmds:
      - echo "Function app upload is complete"
    desc: Generate function app bin and upload to Azure Storage accounts
