name: 'Function app code distribution'

on:
  workflow_dispatch:
  push:
    branches:
      - add-autoscaling-support
      - distribute-function-zip
    paths:
      - 'function-app/**'

jobs:
  function-app-dist:
    name: Upload function app code 
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}    
    defaults:
      run:
        shell: bash
        working-directory: ./function-app/distribution
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # add to be able to refer to the output correctly
          terraform_wrapper: false

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="subscription_id=${{ secrets.SUBSCRIPTION_ID }}"

      - name: Update Function App Zip Version
        run: |
          new_function_app_zip_version=$(terraform output function_app_zip_md5)
          cd ../../
          old_function_app_zip_version=$(awk '/Function app code version/{getline;print $NF;}' variables.tf)
          sed -i "s/$old_function_app_zip_version/$new_function_app_zip_version/" variables.tf

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update function_app_version'
          file_pattern: 'variables.tf'
          skip_fetch: true    
          skip_checkout: true
