name: Push to main branch

on:
  push:
    branches:
      - main
  
jobs:
  update_app_code_dist:
    name: Update app_code_dist
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update app_code_dist default to 'release'
        run: sed -i 's/^\( *default =\) "dev"/\1 "release"/' variables.tf 

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: set app_code_dist=release'
          file_pattern: 'variables.tf'
